name: Execute SmartUI Test

on:
  push:
    branches:
      - main

env:
  LT_USERNAME: ${{ secrets.LT_USERNAME }}
  LT_ACCESS_KEY: ${{ secrets.LT_ACCESS_KEY }}

jobs:
  playwright-smart-ui:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chromium, webkit, firefox]
        user-agent: [mobile, desktop]
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 10

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Step for push event
        run: |
          echo "This is a push event!"
          echo "The latest commitId $(git log -1 --format='%H')"
          echo "COMMIT_ID=$(git log -1 --format='%H')" >> $GITHUB_ENV
        if: github.event_name == 'push'

      - name: Step for pull_request event
        run: |
          echo "This is a pull_request event!"
          git log -n 5 --format="%H %an %s" | while read line; do echo "$line"; done
          echo "The latest commitId $(git log -n 2 --format='%H' | tail -n 1)"
          echo "COMMIT_ID=$(git log -n 2 --format='%H' | tail -n 1)" >> $GITHUB_ENV

      - name: Create Github URL
        run: |
          API_HOST=https://api.github.com
          echo "The latest commitId is $COMMIT_ID"
          GITHUB_URL=$API_HOST/repos/$GITHUB_REPOSITORY/statuses/$COMMIT_ID
          echo "GITHUB_URL: $GITHUB_URL"
          echo "GITHUB_URL=$GITHUB_URL" >> $GITHUB_ENV

      - name: Install Dependencies
        run: npm install

      - name: Execute SmartUI Test
        run: node playwright-smartui.js